### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by lukeprofits** [tcheeric/nostr-java#101]
New-ish to Java and I'm trying to figure it out. The documentation isn't very extensive.

I tried:
git clone https://github.com/tcheeric/nostr-java

cd nostr-java

mvn clean package

...but it gives errors and then the following doesn't work

java -jar nostr-client.jar

**Comment by tcheeric** [comment]
Hi Luke, 
I encourage you checkout the code from the develop branch. Can you share the errors you get? 
 You may need to install a relay on your machine on localhost:8080, to run the tests without errors. Also, use mvn install instead. 

-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


13 Mar 2024, 19:18 by ***@***.***:

**Comment by tcheeric** [comment]
(I have deleted my previous comment)

Please let me know:
- What branch are you building?
- What errors are you getting?
- Do you use an IDE (Netbeans, or IntelliJ etc) or just command line?

**Comment by lukeprofits** [comment]
Just the master branch. My project that I want to use it in I wrote in IntelliJ, but I was just trying to build it through command line. 

This is what I'm seeing: 

`➜  Java git clone https://github.com/tcheeric/nostr-java
Cloning into 'nostr-java'...
remote: Enumerating objects: 8908, done.
remote: Counting objects: 100% (646/646), done.
remote: Compressing objects: 100% (306/306), done.
remote: Total 8908 (delta 299), reused 463 (delta 239), pack-reused 8262
Receiving objects: 100% (8908/8908), 1.07 MiB | 7.78 MiB/s, done.
Resolving deltas: 100% (4223/4223), done.
➜  Java cd nostr-java
➜  nostr-java git:(main) mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] nostr-java                                                         [pom]
[INFO] nostr-java-util                                                    [jar]
[INFO] nostr-java-crypto                                                  [jar]
[INFO] nostr-java-base                                                    [jar]
[INFO] nostr-java-event                                                   [jar]
[INFO] nostr-java-ws-handler-interface                                    [jar]
[INFO] nostr-java-ws-response-handler-provider                            [jar]
[INFO] nostr-java-ws                                                      [jar]
[INFO] nostr-java-id                                                      [jar]
[INFO] nostr-java-ws-request-handler-provider                             [jar]
[INFO] nostr-java-client                                                  [jar]
[INFO] nostr-java-ws-handler-command-provider                             [jar]
[INFO] nostr-java-api                                                     [jar]
[INFO] nostr-java-examples                                                [jar]
[INFO] nostr-java-test                                                    [jar]
[INFO] 
[INFO] -----------------------< nostr-java:nostr-java >------------------------
[INFO] Building nostr-java 0.3.1                                         [1/15]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ nostr-java ---
[INFO] 
[INFO] ---------------------< nostr-java:nostr-java-util >---------------------
[INFO] Building nostr-java-util 0.3.1                                    [2/15]
[INFO]   from nostr-java-util/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ nostr-java-util ---
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ nostr-java-util ---
[INFO] skip non existing resourceDirectory /Users/[redacted for privacy]/Desktop/Java/nostr-java/nostr-java-util/src/main/resources
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ nostr-java-util ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 6 source files with javac [debug deprecation target 19 module-path] to target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for nostr-java 0.3.1:
[INFO] 
[INFO] nostr-java ......................................... SUCCESS [  0.080 s]
[INFO] nostr-java-util .................................... FAILURE [  0.519 s]
[INFO] nostr-java-crypto .................................. SKIPPED
[INFO] nostr-java-base .................................... SKIPPED
[INFO] nostr-java-event ................................... SKIPPED
[INFO] nostr-java-ws-handler-interface .................... SKIPPED
[INFO] nostr-java-ws-response-handler-provider ............ SKIPPED
[INFO] nostr-java-ws ...................................... SKIPPED
[INFO] nostr-java-id ...................................... SKIPPED
[INFO] nostr-java-ws-request-handler-provider ............. SKIPPED
[INFO] nostr-java-client .................................. SKIPPED
[INFO] nostr-java-ws-handler-command-provider ............. SKIPPED
[INFO] nostr-java-api ..................................... SKIPPED
[INFO] nostr-java-examples ................................ SKIPPED
[INFO] nostr-java-test .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.675 s
[INFO] Finished at: 2024-03-14T08:15:47-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project nostr-java-util: Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :nostr-java-util
➜  nostr-java git:(main) 
`

**Comment by tcheeric** [comment]
I'll have a look. 
-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


14 Mar 2024, 13:19 by ***@***.***:

**Comment by tcheeric** [comment]
Make sure you use java 19. I think the error you are facing is because you are compiling with java 21...

See: https://stackoverflow.com/questions/77171270/compilation-error-after-upgrading-to-jdk-21-nosuchfielderror-jcimport-does-n

**Comment by tcheeric** [comment]
Luke, did it work for you? Let me know if you need more help.

**Comment by kuiperanon** [comment]
> Just the master branch. My project that I want to use it in was written in IntelliJ, but I was just trying to build it through command line.
> 
> This is what I'm seeing:
> 
> `➜ Java git clone https://github.com/tcheeric/nostr-java Cloning into 'nostr-java'... remote: Enumerating objects: 8908, done. remote: Counting objects: 100% (646/646), done. remote: Compressing objects: 100% (306/306), done. remote: Total 8908 (delta 299), reused 463 (delta 239), pack-reused 8262 Receiving objects: 100% (8908/8908), 1.07 MiB | 7.78 MiB/s, done. Resolving deltas: 100% (4223/4223), done. ➜ Java cd nostr-java ➜ nostr-java git:(main) mvn clean package [INFO] Scanning for projects... [INFO] ------------------------------------------------------------------------ [INFO] Reactor Build Order: [INFO] [INFO] nostr-java [pom] [INFO] nostr-java-util [jar] [INFO] nostr-java-crypto [jar] [INFO] nostr-java-base [jar] [INFO] nostr-java-event [jar] [INFO] nostr-java-ws-handler-interface [jar] [INFO] nostr-java-ws-response-handler-provider [jar] [INFO] nostr-java-ws [jar] [INFO] nostr-java-id [jar] [INFO] nostr-java-ws-request-handler-provider [jar] [INFO] nostr-java-client [jar] [INFO] nostr-java-ws-handler-command-provider [jar] [INFO] nostr-java-api [jar] [INFO] nostr-java-examples [jar] [INFO] nostr-java-test [jar] [INFO] [INFO] -----------------------< nostr-java:nostr-java >------------------------ [INFO] Building nostr-java 0.3.1 [1/15] [INFO] from pom.xml [INFO] --------------------------------[ pom ]--------------------------------- [INFO] [INFO] --- clean:3.2.0:clean (default-clean) @ nostr-java --- [INFO] [INFO] ---------------------< nostr-java:nostr-java-util >--------------------- [INFO] Building nostr-java-util 0.3.1 [2/15] [INFO] from nostr-java-util/pom.xml [INFO] --------------------------------[ jar ]--------------------------------- [INFO] [INFO] --- clean:3.2.0:clean (default-clean) @ nostr-java-util --- [INFO] [INFO] --- resources:3.3.1:resources (default-resources) @ nostr-java-util --- [INFO] skip non existing resourceDirectory /Users/[redacted for privacy]/Desktop/Java/nostr-java/nostr-java-util/src/main/resources [INFO] [INFO] --- compiler:3.11.0:compile (default-compile) @ nostr-java-util --- [INFO] Changes detected - recompiling the module! :source [INFO] Compiling 6 source files with javac [debug deprecation target 19 module-path] to target/classes [INFO] ------------------------------------------------------------------------ [INFO] Reactor Summary for nostr-java 0.3.1: [INFO] [INFO] nostr-java ......................................... SUCCESS [ 0.080 s] [INFO] nostr-java-util .................................... FAILURE [ 0.519 s] [INFO] nostr-java-crypto .................................. SKIPPED [INFO] nostr-java-base .................................... SKIPPED [INFO] nostr-java-event ................................... SKIPPED [INFO] nostr-java-ws-handler-interface .................... SKIPPED [INFO] nostr-java-ws-response-handler-provider ............ SKIPPED [INFO] nostr-java-ws ...................................... SKIPPED [INFO] nostr-java-id ...................................... SKIPPED [INFO] nostr-java-ws-request-handler-provider ............. SKIPPED [INFO] nostr-java-client .................................. SKIPPED [INFO] nostr-java-ws-handler-command-provider ............. SKIPPED [INFO] nostr-java-api ..................................... SKIPPED [INFO] nostr-java-examples ................................ SKIPPED [INFO] nostr-java-test .................................... SKIPPED [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE [INFO] ------------------------------------------------------------------------ [INFO] Total time: 0.675 s [INFO] Finished at: 2024-03-14T08:15:47-05:00 [INFO] ------------------------------------------------------------------------ [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project nostr-java-util: Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException [ERROR] [ERROR] After correcting the problems, you can resume the build with the command [ERROR] mvn <args> -rf :nostr-java-util ➜ nostr-java git:(main) `

> java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' 

For me this was resolved with: https://github.com/tcheeric/nostr-java/issues/119

**Comment by tcheeric** [comment]
Yes, that should fix it. 
-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


5 Apr 2024, 14:29 by ***@***.***:
