### ISSUE TITLE
NIP46 request is not structured correctly

### ISSUE THREAD

**Issue by kuiperanon** [tcheeric/nostr-java#123]
As of b3b6aae659411f57c413827e38ba6a80d0d02a0b, the structure of the NIP-46 request ([nostr.api.NIP46.Request](https://github.com/tcheeric/nostr-java/blob/develop/nostr-java-api/src/main/java/nostr/api/NIP46.java#L63)) is not correct. 

According to documentation, the request should be of the following structure:

```
{
    "id": <random_string>,
    "method": <method_name>,
    "params": [array_of_strings]
}
```
(Source: https://github.com/nostr-protocol/nips/blob/master/46.md#request-events-kind-24133)

I made related comments here: https://github.com/tcheeric/nostr-java/commit/b3b6aae659411f57c413827e38ba6a80d0d02a0b
 
In the meantime, I'll work on creating a simple test to produce the problem I expect from this code.

**Comment by kuiperanon** [comment]
I added this test to nostr-java-test:

```java
    @Test
    public void testCreateNIP46Request() {
        NIP46.Request req = NIP46.Request.fromString("{\"id\":\"foobar\", \"method\":\"connect\", \"params\": [\"123fakepublickey\"]}");
        System.out.println("testCreateNIP46Request:");
        System.out.println(req.toString());
        assertTrue(true);
    }
```

I believe this stringified JSON should be accepted by NIP46.Request.fromString, because it is a correctly structured NIP-46 request per the guide. However we get this:

```
java.lang.RuntimeException:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id" (class nostr.api.NIP46$Request), not marked as ignorable (5 known properties: "token", "requestUuid", "createdAt", "initiator", "parameters"])
 at [Source: (String)"{"id":"foobar", "method":"connect", "params": ["123fakepublickey"]}"; line: 1, column: 8] (through reference chain: nostr.api.NIP46$Request["id"])
	at nostr.test.api.NIP46Test.testCreateNIP46Request(NIP46Test.java:20)
```

I'm going to write a PR that fixes this.

**Comment by tcheeric** [comment]
Yeah, I came up with this request class, while working on a remote signing app. It was before they added it in the spec. I will have to make the changes, but it also means I have to redesign my remote signer app as well, to remain compliant. :(

**Comment by kuiperanon** [comment]
I am using code like this to test the NIP46. 

I'm not sure if this is correct yet, I don't understand the response messages I'm getting from the relay.

https://gist.github.com/kuiperanon/1186d56de51173da0cb69ce25351393b

**Comment by kuiperanon** [comment]
After researching the nostr protocol and this library, I've discovered that this library serializes FilterLists in the REQ messages incorrectly. I will write up an issue
