### ISSUE TITLE
REQ message filters are not serialized correctly

### ISSUE THREAD

**Issue by kuiperanon** [tcheeric/nostr-java#124]
REQ messages should be in the following format:

`["REQ", <subscription_id>, <filters1>, <filters2>, ...]`

However this library incorrectly serializes REQ messages like this:

`["REQ", <subscription_id>, [<filters1>, <filters2>, ...]]`

Source: https://github.com/nostr-protocol/nips/blob/master/01.md#from-relay-to-client-sending-events-and-notices

**Comment by kuiperanon** [comment]
I don't know how to use fasterxml, so I need to research how to do this.

**Comment by tcheeric** [comment]
Assign to me. 
-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


30 Mar 2024, 20:22 by ***@***.***:

**Comment by kuiperanon** [comment]
Ok, Thanks!

**Comment by kuiperanon** [comment]
I dont know how to assign. Btw

**Comment by tcheeric** [comment]
No problem. I'll grab it. Thanks
-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


31 Mar 2024, 02:35 by ***@***.***:

**Comment by kuiperanon** [comment]
Your fix passes my test.

**Comment by kuiperanon** [comment]
["REQ","...",{"ids":["...."]}]

I passed in an ids filter. It looks right!
