### ISSUE TITLE
Client.serverURI should handle hostname with "wss://" or "ws://" scheme prefixes

### ISSUE THREAD

**Issue by kuiperanon** [tcheeric/nostr-java#126]
Low priority.

Currently, Client.serverURI() will only properly handle hostnames lacking a scheme prefix. The function should properly handle the case when the hostname passed in begins with "wss://" or "ws://".

**Comment by tcheeric** [comment]
Actually, you're not supposed to. It gets added automatically. But maybe this is not intuitive, and it should be handled. I'll think about it. 
I need to redesign that class anyway, I've discovered its limitations while working on nip-42.

-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


3 Apr 2024, 02:52 by ***@***.***:

**Comment by kuiperanon** [comment]
Yeah I think it's just less intuitive. It's not a critical bug

**Comment by tcheeric** [comment]
The app is trying to figure out whether SSL is supported or not. This requires probing the secure connection, and if successful, it will default to wss connections, else ws.

This is cumbersome, unnecessary and not good for performance. The scheme should be added in the configuration file, e.g. ```ws://localhost:5555```
