### ISSUE TITLE
Bouncy Castle Denial of Service (DoS)

### ISSUE THREAD

**Issue by tcheeric** [tcheeric/nostr-java#134]
Package: org.bouncycastle:bcprov-jdk15on (Maven)

Affected versions: <= 1.70

Patched version: None

Bouncy Castle for Java before 1.73 contains a potential Denial of Service (DoS) issue within the Bouncy Castle org.bouncycastle.openssl.PEMParser class. This class parses OpenSSL PEM encoded streams containing X.509 certificates, PKCS8 encoded keys, and PKCS7 objects. Parsing a file that has crafted ASN.1 data through the PEMParser causes an OutOfMemoryError, which can enable a denial of service attack.

https://github.com/tcheeric/nostr-java/security/dependabot/3

**Comment by kuiperanon** [comment]
I get a 404 from that link.

**Comment by tcheeric** [comment]
Same as #135
