### ISSUE TITLE
Unable to parse/serialize BaseTag with JSON number field values

### ISSUE THREAD

**Issue by kuiperanon** [tcheeric/nostr-java#146]
Because `getFieldValue` returns a string, TagSerializer coerces all tag values as strings. So that if you define a subclass of BaseTag that as an Integer field value, it will serialize as a JSON string instead of a JSON number.

**Comment by kuiperanon** [comment]
I'm using the tags which are a List<BaseTag> in GenericEvent which uses TagSerializer.

**Comment by avlo** [comment]
If I'm understanding @kuiperanon issue correctly, @tcheeric suggested solution is correct (or in any case, a clean and working option)

> In this case, you would need to create a custom serialiser for your subclass, no?

@kuiperanon, an implementation example can be seen [here](https://github.com/avlo/nostr-java-avlo-fork/blob/3c952649f1077b2c578fd4b424f6ce2b8008f081/nostr-java-event/src/main/java/nostr/event/json/serializer/ClassifiedEventSerializer.java#L18) with the customization hook on [line 26](https://github.com/avlo/nostr-java-avlo-fork/blob/3c952649f1077b2c578fd4b424f6ce2b8008f081/nostr-java-event/src/main/java/nostr/event/json/serializer/ClassifiedEventSerializer.java#L26) and customization implementation class [here](https://github.com/avlo/nostr-java-avlo-fork/blob/3c952649f1077b2c578fd4b424f6ce2b8008f081/nostr-java-event/src/main/java/nostr/event/json/serializer/PriceTagSerializer.java#L13)

**Comment by tcheeric** [comment]
Thanks, @avlo for clarifying this.

**Comment by kuiperanon** [comment]
Ok. I just wasn't sure how the annotations from fasterxml worked, but now I think that they work kind of like virtual function, and so when I construct a subclass of BaseTag, the @JsonSerialize annotated on the subclass will replace the serializer used for that object.

**Comment by kuiperanon** [comment]
And I wrote a test to test my assumption above, and it works! Thanks @avlo

**Comment by kuiperanon** [comment]
I'm gonna close this issue.
