### ISSUE TITLE
Migrat marshall and unmarshall to full Jackson 

### ISSUE THREAD

**Issue by guilhermegps** [tcheeric/nostr-java#15]
It's necessary to improve the marshal to json for using Jackson. It'll make the code cleaner and maintainable.

Something like that [Jackson – Marshal and Unmarshal](https://howtodoinjava.com/jackson/jackson-read-write-json/).

**Comment by tcheeric** [comment]
This is a huge task, it should be done gradually. What do you think?

**Comment by guilhermegps** [comment]
Well, I agree it's a big task, but I already did the largest part of it. What do you think about we create a development environment for test and homolog new tasks like that?

Have you already heard about gitflow?

**Comment by tcheeric** [comment]
Good idea on dev environment. I'm up for it. How do you propose we create it? 
I'm researching gitflow now...

**Comment by guilhermegps** [comment]
We'll change our branch flow for gitflow, and than we we'll have a main branch (like production) and a secundly branch named develop (like homolog). All new features have to be merged on develop when they are ready (and enough tested). When we have enough changes on the develop branch, it will be homologated (to garantee it is stable) and then it will be created a new realese that will be merged on main branch.

All details and others situations are defined on gitflow specifications.

**Comment by guilhermegps** [comment]
Finished. Check #15 and #30

**Comment by tcheeric** [comment]
I am currently testing native modules and I anticipate that I will be finished by Monday next week. There are a lot of changes, so I would prefer to release it separately.

**Comment by tcheeric** [comment]
Hey @guilhermegps, can you push your changes?
