### ISSUE TITLE
Java 17 LTS as minimum

### ISSUE THREAD

**Issue by maxbrito500** [tcheeric/nostr-java#176]
Hello,

Can you please change the settings on the project `pom.xml` to target Java 17 since that is the LTS?

```
<maven.compiler.source>17</maven.compiler.source>
<maven.compiler.target>17</maven.compiler.target>
```

On most VM/servers when deploying are conservative and only make JDK 17 available by default.

I've tested and compiled OK, did not went further yet.

Thanks.

**Comment by avlo** [comment]
you can target compile/deploy 17 as per your needs.  downgrading the version in repository pom is not necessary (nor desirable).

**Comment by maxbrito500** [comment]
Thanks, it was just because the README mentioned 19 as the supported version. For my case I've done as you mention.

Was trying to use the library but was unfortunately not able to use it, the only thing working at the moment is the generation of private/public keys but all the rest was with a lot of errors about missing classes.

The documentation for setting up Maven also took me a while to setup. Maybe possible to correct:

```
<properties>
        <nostr-java.version>0.6.1-SNAPSHOT</nostr-java.version>
    </properties>
```


```
<dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-base</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-crypto</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-event</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-examples</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-id</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-test</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-util</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-connection</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-command-interface</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-command-provider</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-client</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-api</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-encryption</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-encryption-nip04</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-encryption-nip44</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-context</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-context-interface</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-controller</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>

```

This is the most developed library in java for Nostr. I would like to help adding patches and fix where possible but I couldn't solve the current problems that were appearing, it was just incomplete.

Had to write a standalone library to sign nostr events: https://github.com/nostrium/java/blob/main/src/main/java/online/nostrium/utils/NostrSign.java

But still using your library where possible:
https://github.com/nostrium/java/blob/main/src/main/java/online/nostrium/utils/NostrUtils.java#L26


I'll be needing the basic features in either case such as sending messages to the relays and retrieving other info. Instead of writing something separated would prefer to submit contributions here.

**Comment by avlo** [comment]
you should have no issue compiling (and all successful unit/integration tests<sup>1</sup>) using [java 19.0.2](https://www.oracle.com/java/technologies/javase/jdk19-archive-downloads.html)
```bash
$ java -version
java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```
and maven version 3.9.4:
```bash

$ mvn -version
Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: /.../.sdkman/candidates/maven/3.9.4
Java version: 19.0.2, vendor: Oracle Corporation, runtime: /.../jdk-19.0.2
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-118-generic", arch: "amd64", family: "unix"
```

w/ pom maven.compiler version set to 17:
```xml
<maven.compiler.source>17</maven.compiler.source>
<maven.compiler.target>17</maven.compiler.target>
```

_<sup>1</sup>ClientTest test is known/expected to fail if no local relay running_
```bash
[ERROR] ClientTest.disconnect:77 expected: <2> but was: <0>
```

**Comment by avlo** [comment]
also, your pom dependencies might be importing more than required.  see [superconductor/pom.xml](https://github.com/avlo/superconductor/blob/4a512b7aa9c17f48da65efb55220a3b9a42274ab/pom.xml#L92C1-L106C18) for a working reference

**Comment by avlo** [comment]
many dozens of developers compile, use and build upon these libraries without issue, including myself.  since any single person's development environment and settings may vary in ways that are non-standard, which is commonly the reason problems like yours arise, to minimize ambiguities and help troubleshoot your problem, please submit below information:

1. Description: A detailed description of the issue.
2. Environment Settings: java version, maven version, environment path and classpath settings.
3. Steps to reproduce: Clear and specific steps to replicate the issue.
4. Expected behavior: Description of what expected results should be.
5. Actual behavior: Description of what the software is doing instead.

**Comment by tcheeric** [comment]
Brito, It's hosted on jitpack, not mvnreposirory.

--
Sent with Tuta; enjoy secure & ad-free emails:
https://tuta.com


26 Aug 2024, 10:13 by ***@***.***:

**Comment by maxbrito500** [comment]
Thank you @avlo and @tcheeric, that hint was enough to understand what to get fixed. It is now working and I'm a happy user. Will support this library by sharing the notes from newbie perspective.

**Inside pom.xml**

Define the value for the most recent version available:
```
    <properties>
        <nostr-java.version>0.6.1-SNAPSHOT</nostr-java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
```

Add Jitpack to the repositories:
```
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
```

Finally add the dependencies:
```
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-api</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-event</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
        <dependency>
            <groupId>nostr-java</groupId>
            <artifactId>nostr-java-id</artifactId>
            <version>${nostr-java.version}</version>
        </dependency>
```


After this is possible to use the library. For example:
```
        Identity RECIPIENT = Identity.generateRandomIdentity();
        
        System.out.println("NSEC: " + RECIPIENT.getPrivateKey().toBech32String());
        System.out.println("NPUB: " + RECIPIENT.getPublicKey().toBech32String());
```


I'll propose a pull request. I think this ticket can be closed. Thank you for the quick help.
