### ISSUE TITLE
FAILURE! - in nostr.test.event.EventTest testUnmarshallEvent

### ISSUE THREAD

**Issue by tcheeric** [tcheeric/nostr-java#22]
Filters kinds are encoded as array of String, instead of array of integers.

 I believe this is because of 
``@JsonValue String Kind.toString()``

This causes the following error: 
``
testCreateTextNoteEvent
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.613 s <<< FAILURE! - in nostr.test.event.EventTest
testUnmarshallEvent  Time elapsed: 0.108 s  <<< ERROR!
java.lang.ClassCastException: class nostr.types.values.impl.StringValue cannot be cast to class nostr.types.values.impl.NumberValue (nostr.types.values.impl.StringValue and nostr.types.values.impl.NumberValue are in unnamed module of loader 'app')
	at nostr.test.event.EventTest.testUnmarshallEvent(EventTest.java:209)
``

**Comment by guilhermegps** [comment]
Fixed on #21 - Commit: 18be653ed1590b71497d5602a5eedba33ccd1cf6
