### ISSUE TITLE
Client.send() not sending messages (?)

### ISSUE THREAD

**Issue by tcheeric** [tcheeric/nostr-java#26]
When I call the Client.send() from my client app, it doesn't send the message to the relay. It appears it never enters the forEach() section of the parallel stream defined in the method.

In my example below, I am trying to submit a REQ-message containing a filter to extract NIP-4 messages sent to a specific pubkey.

--- exec-maven-plugin:3.1.0:exec (default-cli) @ nostr-bot-client ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Apr 17, 2023 10:42:57 AM nostr.bot.job.NostrJob execute
INFO: Executing job: group1.NostrBotJob executing at 17/04/2023, 10:42,fired by: group1.NostrBotTrigger

Apr 17, 2023 10:42:57 AM nostr.bot.job.impl.AbstractPublisher lambda$publish$0
INFO: Filtering event since 1,681,724,455

Apr 17, 2023 10:42:57 AM nostr.bot.job.impl.AbstractPublisher lambda$publish$0
INFO: Filters: Filters(events=null, authors=null, kinds=BaseList(list=[4]), referencedEvents=null, referencePubKeys=BaseList(list=[f6a04a16b1fb3b4bf40838dacc7f8bd4d46b60d3c9e2a4915877f9a2eac8e323]), since=1681724455, until=null, limit=null, genericTagQueryList=null)

Apr 17, 2023 10:42:57 AM nostr.bot.job.impl.AbstractPublisher lambda$publish$0
**INFO: Sending message ReqMessage(super=GenericMessage(command=REQ, attributes=[], nip=1), subscriptionId=nostr-bot, filters=Filters(events=null, authors=null, kinds=BaseList(list=[4]), referencedEvents=null, referencePubKeys=BaseList(list=[f6a04a16b1fb3b4bf40838dacc7f8bd4d46b60d3c9e2a4915877f9a2eac8e323]), since=1681724455, until=null, limit=null, genericTagQueryList=null))**

Apr 17, 2023 10:42:57 AM nostr.bot.util.BotUtil storeLongToFile
INFO: Storing value 1,681,724,577 to file...

Apr 17, 2023 10:42:59 AM nostr.ws.handler.BaseHandler process
INFO: process

**Comment by guilhermegps** [comment]
Well, it's working for me.

```
INFO: >>> Sending Message: ["REQ","subId1681735158018",{"kinds":[4],"limit":10,"#p":["1b2bc245a06e582d336be4a1dea0ac8fe002189c60dd75ee9144b0d1067afff4"]}]
abr. 17, 2023 9:39:18 AM nostr.ws.ClientListenerEndPoint onTextMessage
FINE: onTextMessage Relay relay.taxi/45.79.20.30:443: Message: ["EVENT","subId1681735158018",{"id":"8771632433ad9860783565f988dc37ab8d8c5102cd4643eb4f4d6d44e2742db2","kind":4,"pubkey":"e0e60948ad94c4901fe63400dddc2633e16c7f960e0212af91f727100a8a1f0f","created_at":1681735149,"content":"nlmEhvtCL06Qr/bm4RBaEw==?iv=owpwBwb46VvewNdf82VgVg==","tags":[["p","1b2bc245a06e582d336be4a1dea0ac8fe002189c60dd75ee9144b0d1067afff4"]],"sig":"a982be0521724a3fb3ff2330f531a02ef267f6feb9b2710d9912736a94e06bead196f51c7d1af44d6958bf687045dfd22f7260f1908a47542fe2fc3cd3d262da"}]
```


What can happens it's that the `Client.send()` is calling before the connection with relays are finished. In this case, we can think in a delay to wait the connection finish. 

Something like what we have in the example class:

```
while(CLIENT.getThreadPool().getCompletedTaskCount() < (RELAYS.size()/2)) {
	Thread.sleep(5000);	
}
```

It not sound like a bug, maybe an improvement.

**Comment by tcheeric** [comment]
Yeah, I might be doing something wrong, because the examples are indeed working fine...
Ok for the delay, I'll give it a try.

**Comment by tcheeric** [comment]
Got it working now, thanks!

PS:  I had to use a do...while loop instead of a while loop for me to work. Maybe because I am testing with only one relay (?)
