### ISSUE TITLE
Remove unnecessary modules/classes/methods

### ISSUE THREAD

**Issue by tcheeric** [tcheeric/nostr-java#29]
- [x] The unmarshaller classes are completely irrelevant to the protocol and can be removed.
- [x] Same for the parser classes, they are now obsolete
- [x] That means we can get rid of nostr-types and nostr-json modules.

**Comment by tcheeric** [comment]
@guilhermegps - I figured out that the only place the unmarshaller classes were useful was in the unit tests. They helped to easily create an element object (event, tag, or message) based on its string representation. It was handy, but can also be achieved in a different way...

**Comment by guilhermegps** [comment]
Sounds good for me. 

We can use Jackson for the same propose. Using Jackson's JsonNode and ArrayNode, we may have fast access to the values serialized and deserialized. We also can use jackson to convert these values to java native types as "String", "Boolean", etc.

**Comment by tcheeric** [comment]
This is completed.
