### ISSUE TITLE
Use jackson API to decode json (un-marshalling)

### ISSUE THREAD

**Issue by tcheeric** [tcheeric/nostr-java#30]
- [x] InternetIdentifierMetadataEvent.setContent()
 - [x] Nip05Validator.getPublicKey()
 - [x] Connection.updateRelayMetadata()
 - [x] Move the Nip05Validator functionality to nostr-util module, either as a class or as a static method within the NostrUtil class
 - [x] more ?...

**Comment by tcheeric** [comment]
@guilhermegps 

I have put my changes (#29) in `guilhermegps-feature/types_marshall_jackson`. I will push them to github, so that you can add yours (#30) on top. 

I have tried to make it easier for you and marked the relevant places with 
`TODO #30` 

Thanks.

**Comment by tcheeric** [comment]
Awesome, thanks. I wasn't sure which branch to check. I'll have a look, cheers
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



8 May 2023, 14:31 by ***@***.***:

**Comment by tcheeric** [comment]
Hi @guilhermegps, I'm not seeing your changes on the branch. So, I think there's been some misunderstandings, and we've been talking past each other. :-)
I've listed in the description above, all the places in the code where we're still using the nostr-json for un-marshaling, and I was hoping you would re-implement it to use the jackson library instead...
Let me know what you think. Thanks.

**Comment by guilhermegps** [comment]
Hi @tcheeric, well we had some misunderstandings. Actually we have 2 kinds of work to do, the firts is what is discribed on #29, we need to remove all unncessary classes like "types" and etc. Secundly we need to re-implement all necessary unmarshellers using jackson.

I don't know what changes you did, so, if you prefer I can do this ignoring your modification on code. 

Or... You can get my changes (just what was discribed on #24) and merge with your changes and then open an PR to develop. In this case we will have all changes before to start other works.

**Comment by tcheeric** [comment]
Hi Guilherme, I did the first part and pushed it to this branch: guilhermegps-feature/types_marshall_jackson. 

I was hoping for you to do the un-marshaling bit. 

Once completed, we can fully remove the unnecessary maven modules 
Maybe you can just use the same branch? 

Thanks. 
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



14 May 2023, 14:34 by ***@***.***:

**Comment by tcheeric** [comment]
This is done.
