### ISSUE TITLE
"Kind":0 Event failed.

### ISSUE THREAD

**Issue by Memory-of-Snow** [tcheeric/nostr-java#32]
**Describe the bug**
"Kind":0 Event failed and Failed to update profile.

**To Reproduce**
Run metaDataEvent() in NostrExamples.java

**Expected behavior**
Successfully updated profile.

"Causes and solutions"
The member variable profile in MetadataEvent is missing annotation "@JsonIgnore".
Add @JsonIgnore to profile in MetadataEvent.java.

**Comment by tcheeric** [comment]
This should be fixed now. Please confirm.

**Comment by Memory-of-Snow** [comment]
I have confirmed the changes. Thank you.
