### ISSUE TITLE
The RelayInformationDocument class inside the Relay class is using member names that do not match the JSON.

### ISSUE THREAD

**Issue by Memory-of-Snow** [tcheeric/nostr-java#36]
**Describe the bug**
The RelayInformationDocument class inside the Relay class is using member names that do not match the JSON.

**To Reproduce**
1. Run NostrExamples.
2. The console displays "UnrecognizedPropertyException: Unrecognized field "supported_nips" (class nostr.base.Relay$RelayInformationDocument), not marked as ignorable (11 known properties: "contact", "pubkey", "software", "version", "limitation", "name", "description", "fees", "paymentsUrl", "supportedNipExtensions", "supportedNips")".

**Additional context**
In the JSON, the correct names to be used are "supported_nips", "supported_nip_extensions", and "payments_url" instead of "supportedNips", "supportedNipExtensions", and "paymentsUrl".

**Comment by tcheeric** [comment]
Correct. This is fixed in the feature/feature_bug_fixes branch. Will merge soon

**Comment by tcheeric** [comment]
Also, please note:

In the new branch, I introduce the ApplicationConfiguration class to configure the other properties file names - Identity (profile.properties), Client (relays.properties), etc. 
You will need an app.properties in the same folder as the jar file, or in your classpath. 
Please look in the code to check how I am using it.

**Comment by Memory-of-Snow** [comment]
The JSONJsonProperty annotation on line 82 of Relay.java in the bugfix branch is "supported_nipd", but it should be "supported_nips", right?

**Comment by tcheeric** [comment]
Yes. Typo. 
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



1 Jun 2023, 09:35 by ***@***.***:

**Comment by tcheeric** [comment]
Fixed
