### ISSUE TITLE
Compatible with 'mention' markers such as 'root' and 'replay’

### ISSUE THREAD

**Issue by Memory-of-Snow** [tcheeric/nostr-java#37]
**Is your feature request related to a problem? Please describe.**
Compatible with mention markers such as 'root' and 'replay’

**Describe the solution you'd like**
Add mention marker to Marker.java

**Additional context**
The information about mention markers can be found at https://github.com/nostr-protocol/nips/blob/master/10.md.

**Comment by guilhermegps** [comment]
Solved on #38

**Comment by Memory-of-Snow** [comment]
As of June 30, 2023, the Marker.java file in the feature/feature_bug_fixes branch has been removed again.
