### ISSUE TITLE
When connecting to certain relays, there is a failure in converting to RelayInformationDocument.

### ISSUE THREAD

**Issue by Memory-of-Snow** [tcheeric/nostr-java#41]
Describe
When connected to certain relays, 
there is an item in RelayInformation that is not specified in NIP-11 called "id," causing a failure in converting it to Relay.RelayInformationDocument.

Additional context
The relay that is using nostr-rs-relay returns an item called "id" in RelayInformation.
I couldn't determine whether nostr-java or nostr-rs-relay is at fault.

https://github.com/nostr-protocol/nips/blob/master/11.md

**Comment by tcheeric** [comment]
Of its not in the nip, then we probably don't have an attribute for it, and it will need to get added.

**Comment by tcheeric** [comment]
I am currently adding the optional attribute. Can you please confirm:
- The type: String, int, long?
- The class name: Relay.RelayInformationDocument?

Thanks.

**Comment by Memory-of-Snow** [comment]
It looks like a String.For Example wss://relay.snort.social
```JSON
{
  "id": "wss://relay.snort.social/",
  "name": "Snort Relay",
  "description": "decent nostr relay",
  "pubkey": "63fe6318dc58583cfe16810f86dd09e18bfd76aabc24a0081ce2856f330504ed",
  "contact": "realy@snort.social",
  "supported_nips": [
    1,
    2,
    9,
    11,
    12,
    15,
    16,
    20,
    22,
    33,
    40,
    42
  ],
  "software": "https://git.sr.ht/~gheartsfield/nostr-rs-relay",
  "version": "0.8.8",
  "limitation": {
    "payment_required": false
  }
}
```

**Comment by tcheeric** [comment]
OK, I have added the missing optional String id and pushed to the branch. Should be fixed now.
