### ISSUE TITLE
Is the restriction on the profile name appropriate?

### ISSUE THREAD

**Issue by Memory-of-Snow** [tcheeric/nostr-java#45]
**Describe**
Regarding the profile name, a pattern match is being performed with "\w[\w\-]+\w" in validate() in MetadataEvent.java
Is this restriction unnecessary?

**Additional context**
In"NIP-01," it is only specified as "name: <username>" without any restrictions regarding patterns or character types.

**Comment by tcheeric** [comment]
There used to be one. They may have updated the nip. 
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



15 Jun 2023, 23:11 by ***@***.***:

**Comment by Memory-of-Snow** [comment]
In UserProfile.java, "NIP-05" and "name" are separate fields.
Should the validation be done on the "NIP-05" field?

**Comment by tcheeric** [comment]
You are correct. This should now be rectified on the branch.

**Comment by Memory-of-Snow** [comment]
For example, 'kind0' of 'fuatjaf' is in the following format.
{
  "name": "fiatjaf",
  "about": "conditional chaining is a shitcoin",
  "picture": "https://fiatjaf.com/static/favicon.jpg",
  "nip05": "_@fiatjaf.com",
  "lud16": "fiatjaf@zbd.gg"
}

Both the 'name' field and the 'nip05' field are required.

**Comment by Memory-of-Snow** [comment]
In that regard, validation for the <local-part> of the "NIP-05" field is required.

**Comment by Memory-of-Snow** [comment]
In that regard, validation for the 'local-part' of the "NIP-05" field is required.
