### ISSUE TITLE
In TagDeserializer.java, when the code is "nonce", both nodeNonce and nodeDifficulty are set to node.get(1).

### ISSUE THREAD

**Issue by Memory-of-Snow** [tcheeric/nostr-java#69]
**Describe the bug**
In TagDeserializer.java, when the code is "nonce", both nodeNonce and nodeDifficulty are set to node.get(1).

**Expected behavior**
Most likely, nodeDifficulty should reference node.get(2).

**Additional context**
Does nonce fit within the range of an Integer data type? Is it possible for larger numbers to be included?

**Comment by tcheeric** [comment]
This has been merged already.
