### ISSUE TITLE
Could not transfer artifact com.tcheeric:nostr-schnorr:pom:0.1-SNAPSHOT

### ISSUE THREAD

**Issue by TiGz** [tcheeric/nostr-java#7]
Hi there - this looks like a really useful collection of stuff for playing with Nostr in Javaland... so thank you for that!

Just having a problem building as the HEAD seems to be missing this shnorr dependency that I couldn't see on Github.

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>nostr-schnorr</artifactId>
            <version>${project.version}</version>
        </dependency>

cheers! :0)

**Comment by tcheeric** [comment]
Thanks for letting me know. I had renamed this artifact to nostr-crypto. I probably need to do some cleanup. I will look look into it later in the evening.

Cheers.

**Comment by tcheeric** [comment]
@TiGz - I have removed all stale references to that artifact. It should now build. Please try and let me know.

**Comment by TiGz** [comment]
@tcheeric brilliant - all good now... thanks very much!

**Comment by tcheeric** [comment]
Thanks for reporting this. I hope you find the code useful. Looking forward to more suggestions...
