### ISSUE TITLE
Multiple filters per `REQ` request

### ISSUE THREAD

**Issue by theborakompanioni** [tcheeric/nostr-java#88]
Sorry if this came up before (did a search and found nothing).
I am trying to create multiple filters, nothing too complex..
e.g. (KIND 1 from Pubkey A) or (KIND 30 from Pubkey B) in a single subscription.

Shouldn't the `ReqMessage` have the ability to specify multiple `Filters` objects?

**Comment by tcheeric** [comment]
Hi there, 

You are correct. I've just reviewed the specification (nip01), and it states:

>A REQ message may contain multiple filters. In this case, events that match any of the filters are to be returned, i.e., multiple filters are to be interpreted as || conditions.

This seems to have changed since I implemented it, and I'll have to update the code. Right now, it's not possible.
