### ISSUE TITLE
Refactor all NIPs according to the new pattern

### ISSUE THREAD

**Issue by guilhermegps** [tcheeric/nostr-java#92]
Status list:

- Working
- Done
- Merged

Progress of work:

**NIP - Developer - Status**
- [x] NIP-01 - @guilhermegps - Merged 
- [x] NIP-02 - @tcheeric  - Merged
- [x] NIP-03 - @tcheeric - Merged
- [x] NIP-04 - @guilhermegps - Merged 
- [x] NIP-05 - @guilhermegps - Merged 
- [x] NIP-08 - @guilhermegps - Merged 
- [x] NIP-09 - @guilhermegps - Merged 
- [x] NIP-12 - @tcheeric - Merged
- [x] NIP-14 - @tcheeric - Merged
- [x] NIP-15 - @tcheeric - Merged
- [x] NIP-16 - @guilhermegps - Merged 
- [x] NIP-20 - @tcheeric - Merged
- [x] NIP-23 - @tcheeric - Merged
- [x] NIP-25 - @guilhermegps - Merged 
- [x] NIP-28 - @tcheeric - Merged
- [x] NIP-30 - @guilhermegps - Merged 
- [x] NIP-31 - @tcheeric - Merged
- [x] NIP-32 - @tcheeric - Merged
- [x] NIP-33 - @guilhermegps - Merged 
- [x] NIP-40 - @tcheeric - Merged
- [x] NIP-42 - @tcheeric - Merged
- [x] NIP-46 - @tcheeric - Merged
- [x] NIP-57 - @tcheeric - Merged

**Comment by tcheeric** [comment]
I complete the remaining NIPs. I have also completed NIP44, and will add on top.
